import { Metadata } from 'next'

import { IntroSection } from '@/components/intro-section'
import { IntroCode } from '@/components/intro-code'
import { SectionHeading } from '@/components/section-heading'
import { AboutAuthor } from '@/components/about-author'
import { FeaturedRepos } from '@/components/featured-repos'
import { HomeTechStack } from '@/components/home-tech-stack'
import { ThemeSwitcher } from '@/components/theme-switcher'


export const metadata: Metadata = {
  title: 'HOME - Gratia',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div className="w-full max-w-5xl mx-auto px-4 py-8 sm:py-16 space-y-12">
      <div className="fixed bottom-4 right-4 z-50 sm:top-4 sm:right-4 sm:bottom-auto">
        <ThemeSwitcher />
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
        <IntroSection />
        <IntroCode />
      </div>
      <section className="space-y-12">
        <SectionHeading>About &amp; Tech</SectionHeading>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          <AboutAuthor />
          <HomeTechStack />
        </div>
      </section>
      <section className="space-y-12">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="lg:col-span-2">
            <SectionHeading>Project Experience</SectionHeading>
            <div className="w-full overflow-hidden h-40 relative">
              <img src="https://algora.io/og/user/clovu" alt="Algora Profile" className="size-full h-auto absolute -top-4.25 -left-4.25" />
            </div>
          </div>

          <div className="lg:col-span-1">
            <SectionHeading>Featured Repos</SectionHeading>
            <FeaturedRepos />
          </div>
        </div>
      </section>
    </div>
  )
}
